/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'canteen',
    path: '/canteen',
    component: 'layout.base',
    meta: {
      title: 'canteen',
      i18nKey: 'route.canteen'
    },
    children: [
      {
        name: 'canteen_building',
        path: '/canteen/building',
        component: 'view.canteen_building',
        meta: {
          title: 'canteen_building',
          i18nKey: 'route.canteen_building'
        }
      },
      {
        name: 'canteen_window',
        path: '/canteen/window',
        component: 'view.canteen_window',
        meta: {
          title: 'canteen_window',
          i18nKey: 'route.canteen_window'
        }
      }
    ]
  },
  {
    name: 'dish',
    path: '/dish',
    component: 'layout.base$view.dish',
    meta: {
      title: 'dish',
      i18nKey: 'route.dish'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_announcement',
        path: '/monitor/announcement',
        component: 'view.monitor_announcement',
        meta: {
          title: 'monitor_announcement',
          i18nKey: 'route.monitor_announcement'
        }
      },
      {
        name: 'monitor_complaint',
        path: '/monitor/complaint',
        component: 'view.monitor_complaint',
        meta: {
          title: 'monitor_complaint',
          i18nKey: 'route.monitor_complaint'
        }
      },
      {
        name: 'monitor_order',
        path: '/monitor/order',
        component: 'view.monitor_order',
        meta: {
          title: 'monitor_order',
          i18nKey: 'route.monitor_order'
        }
      }
    ]
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base$view.order',
    meta: {
      title: 'order',
      i18nKey: 'route.order'
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user'
    },
    children: [
      {
        name: 'user_merchant',
        path: '/user/merchant',
        component: 'view.user_merchant',
        meta: {
          title: 'user_merchant',
          i18nKey: 'route.user_merchant'
        }
      },
      {
        name: 'user_student',
        path: '/user/student',
        component: 'view.user_student',
        meta: {
          title: 'user_student',
          i18nKey: 'route.user_student'
        }
      }
    ]
  }
];
